# Jekyll Configuration for Decentraland Offline Setup Assistant Documentation

# Site Settings
title: "Decentraland Offline Setup Assistant"
description: "Experience the full Decentraland metaverse offline - no wallet, no browser, no internet required!"
baseurl: "/decentraland"
url: "https://decentraland-org.github.io"

# Author
author:
  name: "Decentraland Community"
  email: "community@decentraland-offline.com"

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  features:
    output: true
    permalink: /:collection/:name/
  advanced:
    output: true
    permalink: /:collection/:name/
  contributing:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Installation"
    url: /installation/
  - title: "Features"
    url: /features/
  - title: "Advanced"
    url: /advanced/
  - title: "Contributing"
    url: /contributing/
  - title: "GitHub"
    url: https://github.com/Decentraland-org/decentraland

# SEO Settings
lang: en_US
timezone: UTC

# Social Media
social:
  name: Decentraland Offline Setup Assistant
  links:
    - https://github.com/Decentraland-org/decentraland
    - https://discord.gg/decentraland
    - https://twitter.com/decentraland

# Google Analytics (if needed)
# google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include
include:
  - _pages

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Comments (if using Disqus)
# disqus:
#   shortname: decentraland-offline

# Search
search_enabled: true
search_tokenizer_separator: /[\s\-/]+/

# Footer
footer_content: "Made with ❤️ for the Decentraland Community | Bringing the Metaverse Offline"

# Custom CSS
custom_css: |
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
    margin: 20px 0;
  }
  
  .card {
    border: 1px solid #e1e4e8;
    border-radius: 6px;
    padding: 20px;
    background: #f6f8fa;
  }
  
  .card h3 {
    margin-top: 0;
    color: #0366d6;
  }
  
  .btn {
    display: inline-block;
    padding: 8px 16px;
    background: #0366d6;
    color: white;
    text-decoration: none;
    border-radius: 4px;
    transition: background 0.2s;
  }
  
  .btn:hover {
    background: #0256cc;
    color: white;
    text-decoration: none;
  }

# Gaming-specific metadata
game_info:
  genre: "Virtual World"
  platform: "PC, Mac, Linux"
  rating: "Everyone"
  features:
    - "Offline Virtual World"
    - "Avatar Customization"
    - "Scene Exploration"
    - "Asset Viewing"
    - "No Cryptocurrency Required"

# Technical metadata
tech_stack:
  - "Unity Engine"
  - "C#"
  - "WebGL"
  - "JavaScript"
  - "Jekyll (Documentation)"

# SEO Keywords
keywords:
  primary:
    - "decentraland offline"
    - "metaverse offline"
    - "virtual world offline"
    - "decentraland desktop"
    - "blockchain game offline"
  secondary:
    - "avatar customization"
    - "NFT viewer offline"
    - "virtual reality offline"
    - "web3 game desktop"
    - "decentraland setup assistant"
  long_tail:
    - "how to play decentraland without wallet"
    - "decentraland offline setup guide"
    - "enterprise decentraland installation"
    - "airgapped metaverse client"
    - "portable decentraland setup" 